---
- name: SYSTEMD | STOP SNAPD
  systemd:
    name: snapd
    state: stopped
  failed_when: false

- name: APT | REMOVE SNAP
  apt:
    name: snapd
    state: absent
    purge: true
  when:
    - ansible_os_family == 'Debian'
  failed_when: false
