---
- name: GATHER FACTS
  setup:

- name: INSTALL WIREGUARD
  import_tasks: 'install/ubuntu.yml'

- name: FETCH WIREGUARD PEER CONF
  get_url:
    url: '{{ wireguard_server_url }}/{{ peer }}/{{ peer }}.conf'
    url_username: '{{ wireguard_username }}'
    url_password: '{{ wireguard_password }}'
    dest: /etc/wireguard/wg0.conf
    mode: 0644
    timeout: 30
    use_proxy: false
  register: peer_conf
  retries: 5
  delay: 30
  become: true
  ignore_errors: true

- name: START WIREGUARD AT BOOT
  systemd:
    name: wg-quick@wg0
    state: started
    enabled: true
