---
- name: "ZEROTIER GPG KEY"
  apt_key:
    url: |
      https://raw.githubusercontent.com
      /zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg
    state: present
  when:
    - ansible_os_family == 'Debian'

- name: "ZEROTIER APT REPOSITORY"
  apt_repository:
    repo: |
      deb [arch=amd64] https://apt.releases.hashicorp.com \
      {{ ansible_distribution_release }} main
    state: present
  when:
    - ansible_os_family == 'Debian'

- name: "APT INSTALL ZEROTIER"
  apt:
    name: terraform
    update_cache: true
    state: present
  when:
    - ansible_os_family == 'Debian'
