---
- name: APT | INSTALL NGINX
  apt:
    name: nginx
    state: present
    update_cache: true
- name: UFW | ENABLE NGINX
  community.general.ufw:
    name: Nginx Full
    log: true
    rule: allow
- name: NGINX | APPLY CONFIG
  become: true
  template:
    src: 'default.conf.j2'
    dest: /etc/nginx/conf.d/default.conf
    mode: +r
    owner: root
    group: root
- name: SYSTEMD | ENABLE NGINX
  systemd:
    enabled: true
    state: started
    name: nginx
