---
- name: 'APT | KVM PACKAGES'
  apt:
    name: '{{ apt_packages }}'
    update_cache: true
    state: present
  when:
    - ansible_os_family == 'Debian'

- name: 'NETPLAN | NETCFG.YML'
  become: true
  template:
    src: '01-netcfg.yaml.j2'
    dest: /etc/netplan/01-netcfg.yaml
    mode: +r
    owner: root
    group: root

- name: 'NETPLAN | NETPLAN APPLY'
  become: true
  command:
    cmd: netplan apply
  when: true

- name: LIBVIRT | PREPARE
  import_tasks: libvirt.yml

- name: COCKPIT | PREPARE
  import_tasks: cockpit.yml

- name: UBUNTU | DOWNLOAD
  import_tasks: ubuntu.20.04.yml

- name: REBOOT
  reboot:
    connect_timeout: 60
