---
all:
  hosts:
    ac:
    vps:
    hp1-local:
    hp2-local:
    hp3-local:
    lnv1-local:
    vultr-set1-node1:
    vultr-set1-node2:
    vultr-set1-node3:
  children:
    vultr-set1:
      hosts:
        vultr-set1-node1:
        vultr-set1-node2:
        vultr-set1-node3:
    kube_control_plane:
      hosts:
        lnv1-local:
        hp2-local:
    etcd:
      hosts:
        lnv1-local:
        hp2-local:
        hp1-local:
    kube_node:
      hosts:
        lnv1-local:
        hp2-local:
        hp1-local:
    calico_rr:
      hosts: {}
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
        calico_rr:
    homenet:
      hosts:
        hp1-local:
        hp2-local:
        hp3-local:
        lnv1-local:
    cluster:
      hosts:
        hp1-local:
        hp2-local:
        lnv1-local:
    support:
      hosts:
        hp3-local:
