---
- name: SSH | PUBLIC KEY
  become: true
  authorized_key:
    user: rundeck
    key: "{{ lookup('file','/vagrant/hlci_ansible.pub') }}"
- name: SSH | DIRECTORY
  file:
    name: /home/rundeck/.ssh
    group: rundeck
    owner: rundeck
    mode: u=rwX,g=rwX,o=r
    state: directory
  become: true

- name: SYSTEMD | DIRECTORY
  file:
    name: /home/rundeck/.config/systemd/user
    group: rundeck
    owner: rundeck
    mode: u=rwX,g=rwX,o=r
    state: directory
  become: true

- name: SSH | AGENT CONFIG
  copy:
    content: |
      [Unit]
      Description=SSH key agent

      [Service]
      Type=simple
      Environment=SSH_AUTH_SOCK=%t/ssh-agent.socket
      ExecStart=/usr/bin/ssh-agent -D -a $SSH_AUTH_SOCK

      [Install]
      WantedBy=default.target
    dest: /home/rundeck/.config/systemd/user/ssh-agent.service
    owner: rundeck
    group: rundeck
    mode: u=rw,g=rw
  become: true
- name: SSH | PRIVATE KEY
  copy:
    src: /vagrant/hlci_ansible
    dest: /home/rundeck/.ssh/hlci_ansible
    owner: rundeck
    group: rundeck
    mode: 0400
- name: SSH | LOCAL CONFIG
  copy:
    content: |
      Host *
        UserKnownHostsFile=/dev/null
        StrictHostKeyChecking no
        PasswordAuthentication no
        IdentitiesOnly yes
        ForwardAgent yes
        ForwardX11 yes
        IdentityAgent SSH_AUTH_SOCK
        AddKeysToAgent yes
        IdentityFile ~/.ssh/hlci_ansible
        User rundeck
        LogLevel FATAL
    dest: /home/rundeck/.ssh/config
    owner: rundeck
    group: rundeck
    mode: u=rw
- name: SYSTEMD | ENABLE SSH_AGENT
  systemd:
    name: ssh-agent
    state: restarted
    enabled: true
    daemon_reload: true
  failed_when: false
