---
name: "hlci ci"

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: lint Dockerfile
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: "**Dockerfile"
          recursive: true
    