---
name: "hlci ci"

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

jobs:
  lint:
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: lint Dockerfile
        uses: hadolint/hadolint-action@v2.0.0
        if: always()
        with:
          dockerfile: "**Dockerfile"
          recursive: true

      - name: lint yaml
        uses: karancode/yamllint-github-action@master
        if: always()
        with:
          yamllint_file_or_dir: '.'
          yamllint_strict: false
          yamllint_comment: true
